output:queue_LL.o insert.o deletion.o display.o
		gcc queue_LL.c insert.c deletion.c display.c -o queue_out
queue_LL.o:queue_LL.c
	gcc -c queue_LL.c
insert.o:insert.c
	gcc -c insert.c
deletion.o:deletion.c
	gcc -c deletion.c
display.o:display.c
	gcc -c display.c

