output:stack_LL.o push.o pop.o display.o
	gcc stack_LL.c push.c pop.c display.c -o stack_out
stack_LL.o:stack_LL.c
	gcc -c stack_LL.c
push.o:push.c
	gcc -c push.c
pop.o:pop.c
	gcc -c pop.c
display.o:display.c
	gcc -c display.c

